title: Learn basics
author: Nazerke Shaldanbayeva
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The course is getting me through tasks to learn it better

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
